version: '3.5'
services:

  db:
    image: postgres
    container_name: sneakers_23_store_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sneakers_23_dev
    restart: always
    ports:
    - '5432:5432' 
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:  